version: "3"

services:
  api:
    build: api
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    build: db
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data

#  redisinsight:
#    image: redislabs/redisinsight:latest
#    ports:
#      - "8001:8001"
#    depends_on:
#      - db